version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.0.1

jobs:
  test:
    working_directory: ~/webpage
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          command: python --version
      - run:
          command: pip install -r requirements.txt

  deploy-gcp:
    working_directory: ~/webpage
    executor: gcp-cli/default
    parameters:
      google-project-id:
        type: env_var_name
        default: GOOGLE_PROJECT_ID
      gcloud-service-key:
        type: env_var_name
        default: GCLOUD_SERVICE_KEY
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name: Deploy to Cloud Build Production
          command: |
            gcloud builds submit --async --config=cloudbuild.yaml .
         
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - test
      - deploy-gcp:
          requires:
            - test
          filters:
            branches:
              only:
                - GCP